services:
  app:
    container_name: napp
    build: .
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - .env
    command: npm run dev

  db:
    image: postgres:15
    container_name: napp-db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
