services:
  app:
    container_name: napp
    build: .
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - napp-db
    env_file:
      - .env
    command: npm run dev

  napp-db:
    image: postgres:15
    container_name: napp-db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - napp-db

volumes:
  pgdata:
